services:
  fastapi:
    build:
      context: .
    container_name: playground-fastapi
    environment:
      DATABASE_PATH: /data/company.sqlite
      FASTAPI_LOG_PATH: /data/fastapi.log
      FASTAPI_BASIC_AUTH_USERNAME: ${FASTAPI_BASIC_AUTH_USERNAME:-admin}
      FASTAPI_BASIC_AUTH_PASSWORD: ${FASTAPI_BASIC_AUTH_PASSWORD:-password}
    ports:
      - "${API_PORT:-8000}:8000"
    restart: unless-stopped
    volumes:
      - ./data:/data
