version: "3.9"

services:
  fastapi:
    user: "${UID}:${GID}"
    build: ./fastapi
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/data

  codegen:
    build: ./library-builder
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: graphql_codegen
    depends_on:
      - fastapi
    volumes:
      - ./:/workspace
    working_dir: /workspace
    user: "${UID}:${GID}"
    command: >
      bash -c "
      echo 'Waiting for API...' &&
      until curl -s http://fastapi:8000/docs > /dev/null; do
        sleep 2;
      done &&
      bash library-builder/generate-client.sh
      "
